### ISSUE TITLE
Hi - capacitors

### ISSUE THREAD

**Issue by dzid26** [TazerReloaded/ValveCloser#1]
Hi,
Could you elaborate a bit about the capacitors you have connected at the input?
https://github.com/CAP1Sup/Intellistep/issues/59#issuecomment-983013998
Why are there two?
What values and what is the purpose? Just supply stability?

I am trying to figure out why A4950 current driver based close loop stepper controllers rapidly loose torque when being "riden" opposite direction with enough speed. I am thinking electric current flips sign due to massive regeneration and that messes up its regulation. Not sure. 
Interestinggly, I achieved best stepper braking force (torque) by just hooking up two 35uF 200V capacitors to motor phases (passivly!!, without controller), but that only does braking, without driving. 
When I saw your two capacitors, alas in completly different position, for a second I thought you were trying the same thing... :)

I feel I need to experiment with slow decay mode of the A4950 chip to have more braking torque.
![image](https://user-images.githubusercontent.com/841061/155422055-277d6c83-a6cb-45de-9fe6-f363644a0fec.png)
But how to transition smoothly from driving to braking, that's a different story. 
Anyyyway...

**Comment by TazerReloaded** [comment]
The capacitors are just for supply stability, because the network cable to the power supply is about 10 meters long. I used two in series because I only had 16V ones but I'm using a 24V supply.
I used 6 wires of the cable for power, 3 for positive, 3 negative, and the remaining 2 for serial communication. So far everything works fine, but I have not tried higher speeds or braking, because it does not matter for this application.
Interesting insights nevertheless, might be useful for the original IntelliStep project!

**Comment by dzid26** [comment]
Thanks - that's what I thought... :)

IntelliStep project seems interesting. 
I was planning to port my [modified MKS_SERVO42B](https://github.com/dzid26/RetroPilot-SERVO42B/tree/openpilot/firmware/src) to S42Bv2 board, so IntelliStep should be useful. I hope BIGTREETECH restarts sales of the board.
